CREATE DATABASE IF NOT EXISTS db_demo
    DEFAULT CHARACTER SET utf8mb4
    COLLATE utf8mb4_0900_ai_ci;

USE db_demo;

CREATE TABLE IF NOT EXISTS `USER` (
  USER_ID INT NOT NULL AUTO_INCREMENT,
  EMAIL VARCHAR(255) NOT NULL UNIQUE,
  USERNAME VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  IS_DELETED CHAR NOT NULL DEFAULT 'N',
  PRIMARY KEY(USER_ID)
);

CREATE TABLE IF NOT EXISTS ROLE (
  ROLE_ID INT NOT NULL AUTO_INCREMENT,
  ROLE VARCHAR(50) NOT NULL,
  PRIMARY KEY(ROLE_ID)
);

CREATE TABLE IF NOT EXISTS USER_ROLE (
    USER_ID INT NOT NULL,
    ROLE_ID INT NOT NULL,
    FOREIGN KEY(USER_ID) REFERENCES `USER` (USER_ID),
    FOREIGN KEY(ROLE_ID) REFERENCES ROLE (ROLE_ID)
);

CREATE TABLE IF NOT EXISTS LOCALE (
    LOCALE_ID INT NOT NULL AUTO_INCREMENT,
    LOCALE_CODE VARCHAR(50) NOT NULL,
    PRIMARY KEY(LOCALE_ID)
);

CREATE TABLE IF NOT EXISTS `LEVEL` (
    LEVEL_ID INT NOT NULL AUTO_INCREMENT,
    `TYPE` VARCHAR(50) NOT NULL,
    PRIMARY KEY(LEVEL_ID)
);

CREATE TABLE IF NOT EXISTS LEVEL_LOCALIZED (
    LEVEL_ID INT NOT NULL,
    LOCALE_ID INT NOT NULL,
    LEVEL_LOCALIZED VARCHAR(50) NOT NULL,
    FOREIGN KEY(LEVEL_ID) REFERENCES `LEVEL` (LEVEL_ID),
    FOREIGN KEY(LOCALE_ID) REFERENCES LOCALE (LOCALE_ID)
);

CREATE TABLE IF NOT EXISTS QUESTION (
    QUESTION_ID INT NOT NULL AUTO_INCREMENT,
    USER_ID INT NOT NULL,
    LINK VARCHAR(255) NOT NULL,
    LEVEL_ID INT NOT NULL,
    IS_FULLY_LOCALIZED BOOL NOT NULL DEFAULT FALSE,
    PRIMARY KEY(QUESTION_ID),
    FOREIGN KEY(LEVEL_ID) REFERENCES `LEVEL` (LEVEL_ID),
    FOREIGN KEY(USER_ID) REFERENCES `USER` (USER_ID)
);

CREATE TABLE IF NOT EXISTS TITLE (
    TITLE VARCHAR(255) NOT NULL,
    LOCALE_ID INT NOT NULL,
    QUESTION_ID INT NOT NULL,
    FOREIGN KEY(LOCALE_ID) REFERENCES LOCALE (LOCALE_ID),
    FOREIGN KEY(QUESTION_ID) REFERENCES QUESTION (QUESTION_ID)
);